name: Deploy main branch

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Create containers
      run: docker-compose up -d
    - name: Use Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
        cache: pip
    - name: Install Python dependencies
      run: pip install -r requirements.txt -r requirements.dev.txt
    - name: use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 16.x
    - name: Install serverless framework
      run: npm install -g serverless
    - name: Install serverless plugins
      run: npm install
    - name: Run tests
      run: python -m pytest
      env:
        API_KEY: admin
        REDIS_HOST: localhost
        REDIS_PORT: 6379
        REDIS_DB: 0
        REDIS_PASS: ''
        DYNAMODB_URL: http://localhost:8001
        DYNAMODB_USAGE_TABLE: usage-table-dev
        DYNAMODB_REGION: localhost
    - name: Deploy to AWS
      run: sls requirements cleanCache && sls deploy
      env:
        SLS_DEBUG: '*'
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        API_KEY: ${{ secrets.API_KEY }}
        REDIS_HOST: ${{ secrets.REDIS_HOST }}
        REDIS_PORT: ${{ secrets.REDIS_PORT }}
        REDIS_DB: 0
        REDIS_PASS: ${{ secrets.REDIS_PASS }}
